name: test

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: testable-firebase-sample-chat-1

    strategy:
      matrix:
        node-version: [18.X]

    steps:
      - name: レポジトリのチェックアウト
        uses: actions/checkout@v3

      - name: Node.js ${{ matrix.node-version }} セットアップ
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: パッケージインストール
        run: yarn install

      - name: firebase-toolsをインストール
        run: yarn add firebase-tools

      - name: エミュレータの起動
        run: yarn emulators:start:firestore &

      - name: エミュレータの起動待機...
        run: sleep 10

      - name: テスト実行
        run: yarn test

      - name: エミュレータのレポートの待機...
        run: sleep 10

      # https://github.com/SonicGarden/firestore-rules-report-action
      # ちゃんと動いてなさそう？
      #
      # - name: coverage request
      #   id: coverageRequest
      #   uses: SonicGarden/firestore-rules-report-action@v1
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     report-url: 'http://127.0.0.1:8080/emulator/v1/projects/fs-sample-open-chat-test:ruleCoverage.html'
